const majuscules = [
  { l: "A", n: 1, t:true},
  { l: "B", n: 1, t:true},
  { l: "C", n: 1, t:true},
  { l: "D", n: 1, t:true},
  { l: "E", n: 1, t:true},
  { l: "F", n: 1, t:true},
  { l: "G", n: 1, t:true},
  { l: "H", n: 1, t:true},
  { l: "I", n: 1, t:true},
  { l: "J", n: 1, t:true},
  { l: "K", n: 1, t:true},
  { l: "L", n: 1, t:true},
  { l: "M", n: 1, t:true},
  { l: "N", n: 1, t:true},
  { l: "O", n: 1, t:true},
  { l: "P", n: 1, t:true},
  { l: "Q", n: 1, t:true},
  { l: "R", n: 1, t:true},
  { l: "S", n: 1, t:true},
  { l: "T", n: 1, t:true},
  { l: "U", n: 1, t:true},
  { l: "V", n: 1, t:true},
  { l: "W", n: 1, t:true},
  { l: "X", n: 1, t:true},
  { l: "Y", n: 1, t:true},
  { l: "Z", n: 1, t:true},
  { l: "!", n: 1, t:true},
]
const minuscules = [
  { l: "a", n: 11, t:false},
  { l: "b", n: 2, t:false},
  { l: "c", n: 2, t:false},
  { l: "d", n: 2, t:false},
  { l: "e", n: 11, t:false},
  { l: "f", n: 2, t:false},
  { l: "g", n: 2, t:false},
  { l: "h", n: 2, t:false},
  { l: "i", n: 7, t:false},
  { l: "j", n: 1, t:false},
  { l: "k", n: 1, t:false},
  { l: "l", n: 4, t:false},
  { l: "m", n: 2, t:false},
  { l: "n", n: 4, t:false},
  { l: "o", n: 7, t:false},
  { l: "p", n: 2, t:false},
  { l: "q", n: 1, t:false},
  { l: "r", n: 4, t:false},
  { l: "s", n: 4, t:false},
  { l: "t", n: 4, t:false},
  { l: "u", n: 7, t:false},
  { l: "v", n: 2, t:false},
  { l: "w", n: 1, t:false},
  { l: "x", n: 1, t:false},
  { l: "y", n: 1, t:false},
  { l: "z", n: 1, t:false},
  { l: ".", n: 8, t:false},
]
const baseDeck = [
  ...majuscules.map((cur) => Array(cur.n).fill({ l: cur.l, t: cur.t })).reduce((prev,cur)=> prev.concat(cur)),
  ...minuscules.map((cur) => Array(cur.n).fill({ l: cur.l, t: cur.t })).reduce((prev,cur)=> prev.concat(cur))
]
export default baseDeck